"""
Shared constants - single source of truth for block types, message types,
and world dimensions. Both server.py and worldgen layers should import from here.
"""

# World dimensions
CHUNK_SIZE = 16
CHUNK_HEIGHT = 64

# Block type IDs - must match client/js/game.js BLOCK_TYPES exactly
BLOCK_TYPES = {
    'AIR': 0,
    'GRASS': 1,
    'DIRT': 2,
    'STONE': 3,
    'WOOD': 4,
    'LEAVES': 5,
    'WATER': 6,
    'SAND': 7,
    'CHEST': 8,
    # Ores
    'COAL_ORE': 10,
    'IRON_ORE': 11,
    'GOLD_ORE': 12,
    'DIAMOND_ORE': 13,
    # Decorative / flora (no dedicated client block yet, render as nearest)
    'FLOWERS': 18,
    'TALL_GRASS': 19,
    # Processed wood / construction
    'LOG': 20,
    'PLANKS': 21,
    'COBBLESTONE': 30,
    'BRICK': 31,
    'GLASS': 32,
    'WOOL': 40,
    'FURNACE': 41,
    'CRAFTING_TABLE': 43,
    # New material source blocks
    'OAK_LOG': 50,
    'PINE_LOG': 51,
    'BIRCH_LOG': 52,
    'OAK_LEAVES': 53,
    'PINE_LEAVES': 54,
    'BIRCH_LEAVES': 55,
    'BERRY_BUSH': 56,
    'THORN_BUSH': 57,
    'HERB_SHRUB': 58,
    'MUSHROOM_CLUSTER': 59,
    'REED_BED': 60,
    'FLINT_NODULE': 61,
    'CLAY_DEPOSIT': 62,
    'SALT_DEPOSIT': 63,
    'COPPER_VEIN': 64,
    'TIN_VEIN': 65,
    'SILVER_VEIN': 66,
    'GEM_SEAM': 67,
    # Workstations
    'CAMPFIRE': 70,
    'TANNING_RACK': 71,
    'CARPENTRY_BENCH': 72,
    'LOOM': 73,
    'SPINNING_WHEEL': 74,
    'MASON_TABLE': 75,
    'FORGE': 76,
    'ANVIL': 77,
    'SMELTER': 78,
    'ALCHEMY_TABLE': 79,
    'ENCHANTING_ALTAR': 80,
    'TAILOR_BENCH': 81,
    'LEATHERWORKER_BENCH': 82,
    'FLETCHING_BENCH': 83,
}

# Reverse lookup: ID -> name
BLOCK_NAMES = {v: k for k, v in BLOCK_TYPES.items()}

# Item type IDs (crafted/dropped items, superset of block types)
ITEM_TYPES = {
    **BLOCK_TYPES,
    # Raw materials
    'STICK': 300,
    'COAL': 301,
    'IRON_INGOT': 302,
    'GOLD_INGOT': 303,
    'DIAMOND': 304,
    # Plant materials
    'WOOD_LOG': 305,
    'BRANCH': 306,
    'BARK': 307,
    'SAP': 308,
    'RESIN': 309,
    'LEAVES': 310,
    'REED': 311,
    'GRASS_FIBER': 312,
    'HEMP_STALK': 313,
    'FLAX_STALK': 314,
    'COTTON_BOLL': 315,
    'VINE': 316,
    'MUSHROOM': 317,
    'HERB': 318,
    'BERRIES': 319,
    'SEEDS': 320,
    'NUTS': 321,
    'ROOTS': 322,
    'FRUIT': 323,
    # Animal materials
    'HIDE': 324,
    'PELT': 325,
    'FUR': 326,
    'WOOL_BUNDLE': 327,
    'SINEW': 328,
    'BONE': 329,
    'ANTLER': 330,
    'HORN': 331,
    'FEATHERS': 332,
    'CLAWS': 333,
    'TEETH': 334,
    'SCALES': 335,
    'MEAT': 336,
    'FAT': 337,
    'MILK': 338,
    'EGGS': 339,
    'BLOOD_VIAL': 340,
    # Stone and earth materials
    'FLINT': 341,
    'GRANITE': 342,
    'SLATE': 343,
    'LIMESTONE': 344,
    'MARBLE': 345,
    'OBSIDIAN': 346,
    'GRAVEL': 347,
    'SAND': 348,
    'CLAY': 349,
    'CHALK': 350,
    'SALT': 351,
    'SULFUR': 352,
    # Metal ores and ingots
    'COPPER_ORE': 353,
    'TIN_ORE': 354,
    'SILVER_ORE': 355,
    'COPPER_INGOT': 356,
    'TIN_INGOT': 357,
    'SILVER_INGOT': 358,
    'BRONZE_INGOT': 359,
    'STEEL_INGOT': 360,
    # Processed materials
    'PLANKS': 361,
    'POLE': 362,
    'CARVED_WOOD': 363,
    'PULP': 364,
    'CHARCOAL': 365,
    'FIBER_BUNDLE': 366,
    'THREAD': 367,
    'TWINE': 368,
    'ROPE': 369,
    'CLOTH_BOLT': 370,
    'FELT': 371,
    'PAPER': 372,
    'HERBAL_PASTE': 373,
    'DYE': 374,
    'FLOUR': 375,
    'PLANT_OIL': 376,
    'DRIED_HERBS': 377,
    'CURED_HIDE': 378,
    'LEATHER': 379,
    'RAWHIDE': 380,
    'BONE_NEEDLE': 381,
    'BONE_PLATE': 382,
    'GLUE': 383,
    'TALLOW': 384,
    'PARCHMENT': 385,
    'CUT_STONE': 386,
    'STONE_BRICK': 387,
    'CERAMIC': 388,
    'POTTERY': 389,
    'GLASS_VIAL': 390,
    'MORTAR': 391,
    'METAL_WIRE': 392,
    'METAL_BAND': 393,
    'NAILS': 394,
    'RIVETS': 395,
    'CHAIN_LINKS': 396,
    # Tools
    'KNIFE': 400,
    'HATCHET': 401,
    'SICKLE': 402,
    'SHOVEL': 403,
    'HAMMER': 404,
    'FISHING_ROD': 405,
    'SKINNING_KNIFE': 406,
    'SHEARS': 407,
    'MORTAR_PESTLE': 408,
    'NEEDLE_SET': 409,
    'HAND_DRILL': 410,
    'TONGS': 411,
    # Food items
    'ROASTED_MEAT': 450,
    'ROASTED_FISH': 451,
    'ROASTED_MUSHROOM': 452,
    'MUSHROOM_SOUP': 453,
    'PORRIDGE': 454,
    'HERB_TEA': 455,
    'JERKY': 456,
    'STEW': 457,
    'BREAD': 458,
    'BERRY_MASH': 459,
    # Weapons
    'WOODEN_SWORD': 100,
    'STONE_SWORD': 101,
    'IRON_SWORD': 102,
    'GOLD_SWORD': 103,
    'DIAMOND_SWORD': 104,
    # Pickaxes
    'WOODEN_PICKAXE': 110,
    'STONE_PICKAXE': 111,
    'IRON_PICKAXE': 112,
    'GOLD_PICKAXE': 113,
    'DIAMOND_PICKAXE': 114,
    # Axes
    'WOODEN_AXE': 120,
    'STONE_AXE': 121,
    'IRON_AXE': 122,
    'GOLD_AXE': 123,
    'DIAMOND_AXE': 124,
    # Armor
    'LEATHER_HELMET': 200,
    'LEATHER_CHESTPLATE': 201,
    'LEATHER_LEGGINGS': 202,
    'LEATHER_BOOTS': 203,
    'IRON_HELMET': 210,
    'IRON_CHESTPLATE': 211,
    'IRON_LEGGINGS': 212,
    'IRON_BOOTS': 213,
    'DIAMOND_HELMET': 220,
    'DIAMOND_CHESTPLATE': 221,
    'DIAMOND_LEGGINGS': 222,
    'DIAMOND_BOOTS': 223,
}

ITEM_NAMES = {v: k for k, v in ITEM_TYPES.items()}

# Stack limits
ITEM_MAX_STACK = {}
for k, v in ITEM_TYPES.items():
    if any(tag in k for tag in ('SWORD', 'PICKAXE', 'AXE', 'HELMET', 'CHESTPLATE', 'LEGGINGS', 'BOOTS')):
        ITEM_MAX_STACK[v] = 1
    else:
        ITEM_MAX_STACK[v] = 64

# WebSocket message types
MESSAGE_TYPES = {
    'JOIN': 'join',
    'REGISTER': 'register',
    'LOGIN': 'login',
    'LOGOUT': 'logout',
    'AUTH_SUCCESS': 'auth_success',
    'AUTH_FAILURE': 'auth_failure',
    'MOVE': 'move',
    'JUMP': 'jump',
    'PLACE_BLOCK': 'place_block',
    'BREAK_BLOCK': 'break_block',
    'INTERACT': 'interact',
    'PLAYER_JOIN': 'player_join',
    'PLAYER_LEAVE': 'player_leave',
    'PLAYER_MOVE': 'player_move',
    'PLAYER_UPDATE': 'player_update',
    'PLAYER_DAMAGE': 'player_damage',
    'PLAYER_HEAL': 'player_heal',
    'PLAYER_DEATH': 'player_death',
    'PLAYER_STATS': 'player_stats',
    'PLAYER_LEVEL_UP': 'player_level_up',
    'WORLD_UPDATE': 'world_update',
    'CHUNK_DATA': 'chunk_data',
    'REQUEST_CHUNK': 'request_chunk',
    'INVENTORY_UPDATE': 'inventory_update',
    'GAME_STATE': 'game_state',
    'OPEN_CONTAINER': 'open_container',
    'CLOSE_CONTAINER': 'close_container',
    'CONTAINER_DATA': 'container_data',
    'MOVE_ITEM': 'move_item',
    'SELECT_QUICKBAR': 'select_quickbar',
    'SPAWN_ITEM_ENTITY': 'spawn_item_entity',
    'REMOVE_ITEM_ENTITY': 'remove_item_entity',
    'COLLECT_ITEM': 'collect_item',
    'TOGGLE_ITEM_LOCK': 'toggle_item_lock',
    'ITEM_LOCK_STATUS': 'item_lock_status',
    'CHAT_MESSAGE': 'chat_message',
    'CHAT_COMMAND': 'chat_command',
    'CHAT_WHISPER': 'chat_whisper',
    'CHAT_SYSTEM': 'chat_system',
    'DROP_ITEM': 'drop_item',
    'CRAFT_ITEM': 'craft_item',
    'CRAFTING_RECIPE': 'crafting_recipe',
    'EQUIP_ITEM': 'equip_item',
    'UNEQUIP_ITEM': 'unequip_item',
    'EQUIPMENT_UPDATE': 'equipment_update',
    'COMBAT_HIT': 'combat_hit',
    'COMBAT_DAMAGE': 'combat_damage',
    'MOB_SPAWN': 'mob_spawn',
    'MOB_DESPAWN': 'mob_despawn',
    'MOB_MOVE': 'mob_move',
    'MOB_ATTACK': 'mob_attack',
    'NPC_SPAWN': 'npc_spawn',
    'NPC_DESPAWN': 'npc_despawn',
    'NPC_INTERACT': 'npc_interact',
    'NPC_DIALOGUE': 'npc_dialogue',
    'NPC_DIALOGUE_RESPONSE': 'npc_dialogue_response',
    'QUEST_ACCEPT': 'quest_accept',
    'QUEST_COMPLETE': 'quest_complete',
    'QUEST_UPDATE': 'quest_update',
    'GIVE_ITEMS': 'give_items',
}
